# Generated by Django 4.1.5 on 2023-01-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publications_change_publications_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='mehtod',
            new_name='meth',
        ),
    ]
