# Generated by Django 4.1.5 on 2023-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Placas de video', 'Placas de video'), ('Procesadores', 'Procesadores'), ('Motherboards', 'Motherboards'), ('Gabinetes', 'Gabinetes'), ('Refrigeracion', 'Refrigeracion'), ('Almacenamiento', 'Almacenamiento'), ('Memorias Ram', 'Memorias Ram'), ('Fuentes', 'Fuentes'), ('Perifericos', 'Perifericos'), ('Monitores', 'Monitores'), ('Otros', 'Otros')], max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('specification', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
        ),
    ]
