# Generated by Django 4.1.5 on 2023-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_components_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='img',
            field=models.ImageField(null=True, upload_to='componentes'),
        ),
    ]
