# Generated by Django 4.1.5 on 2023-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_components_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
